# ---!Ups

CREATE TABLE events (
id BIGINT NOT NULL AUTO_INCREMENT, 
tp VARCHAR(20) CHARACTER SET utf8,
name VARCHAR(100) CHARACTER SET utf8,
date DATE,
dscr TEXT(500) CHARACTER SET utf8,
PRIMARY KEY (id)
);

#---!Downs

DROP TABLE IF EXISTS events